### PR TITLE
Big changes to reduce gl* calls.

### PR DESCRIPTION
**Pull request by MrLarryLi**
I had to make changes to Sparrow for my game (to be released later this year). It seems to have improved the performance on my end. I thought you might be interested in some of the changes I made. I am fairly new to game engines so I am open to suggestions.

### CODE REVIEW

**Comment by PrimaryFeather** [comment]
Hi Larry,
thanks a lot for the extensive pull request and for all your efforts! And sorry for my late reply!

I must admit that I'm currently not doing much native iOS development; and since Sparrow usage is at an all-time low, it's hard to motivate me to make the long-overdue update. Thus, I can't promise any date when I'm going to look into the changes, unfortunately.

I hope Sparrow could still serve your purposes, and you found it interesting to make these changes! I'm always happy to see someone working with the code. :smile:

**Comment by MrLarryLi** [comment]
Hi Daniel,

It's not a problem. Take your time. I will continue to use Sparrow and modify it as I need to. I can let you know when my game is done. Thank you Gamua for all your work on making Sparrow and for making it open source.

**Comment by PrimaryFeather** [comment]
Thanks a lot for the nice word, Larry — and all the best for your game! Yes, please let me know when it's finished, I'd love to take a look at it! :smile:

**Comment by PrimaryFeather** [comment]
Sorry for the troubles! I understand that the huge merge last week with Robert's code was quite a killer for your pull request ... but on the upside, all those changes really push Sparrow forward! =)

I'd be interested in the fixes that are part of the changelist, though, especially your solution to wrap the generics!

**Pull request closed without merging**
