### PR TITLE
Added support for Xcode 6

### PR DESCRIPTION
**Pull request by MrLarryLi**
Hello,

Thank you for the feedback. I managed to redo my fork so now it's cleaner. 

1) I changed glBufferData() because I noticed that it always sends the entire buffer. I do not know how much it impacts performance, but it makes it easier for me to debug.
2) I changed the colors to have alpha because I ran into situations where SPColorWhite wasn't equal to SPColorMakeARGB(255,255,255,255). 
3) As for NSCopying, I did encounter a situation where I called "copy" on one of my sprites. It called the SPSprite "copy" method and didn't call my copyWithZone: method (I can't remember for sure). I did notice something wrong in my game when it happened. That's why I changed them all. It could also be that I don't call [super copy] on my sprites because SPSprite didn't used to implement it. 

Please let me know if there are other things I should do.

### CODE REVIEW

**Comment by racarone** [comment]
Perfect! 

1.) Yeah uploading the full buffer is actually more efficient, at least on iOS devices.
2.) Makes sense, will merge this.
3.) I understand how that can occur now, will merge. =)

Thanks Larry!

**Comment by MrLarryLi** [comment]
I am glad I could help out. 

I do have a request. Could you look into the anti-aliasing? It doesn't seem to work. It generates OpenGL errors about missing depth/stencil buffer when testing for them. I couldn't fix it as I don't have enough understanding about frame buffers.

**Comment by racarone** [comment]
Of course, I'll take a look tomorrow.

**Comment by racarone** [comment]
It's fixed now, the multisample buffer was never being resolved =P

**Comment by MrLarryLi** [comment]
That was fast. Thank you for fixing it.

**Pull request merged**
